/**
 * MARKETING AGENT
 * Role: Brand, content, campaigns
 * Schedule: Every Monday 8am UTC + Wednesday 8am UTC
 *
 * Tasks:
 * 1. Generate full week Instagram caption pack (7 days of ready-to-post copy)
 * 2. Write email newsletter for buyers (wedding planning tips + vendor spotlight)
 * 3. Generate Meta/Google ad copy variants for current season
 * 4. A/B subject line test — split vendor list, send two subject variants, log results
 * 5. Seasonal campaign trigger — detect upcoming South Asian wedding season peaks
 */
import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import Anthropic from '@anthropic-ai/sdk'
import { Resend } from 'resend'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)
const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
const resend = new Resend(process.env.RESEND_API_KEY)
const SITE = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://melaa.ca'
const ADMIN_EMAIL = process.env.ADMIN_EMAIL ?? ''

export const dynamic = 'force-dynamic'

async function ai(prompt: string, tokens = 400): Promise<string> {
  try {
    const r = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001', max_tokens: tokens,
      messages: [{ role: 'user', content: prompt }],
    })
    return (r.content[0] as { type: string; text: string }).text
  } catch { return '' }
}

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url)
  if (searchParams.get('token') !== process.env.AGENT_SECRET)
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const results: string[] = []
  const now = new Date()
  const month = now.getMonth() + 1 // 1-12
  const season = month >= 4 && month <= 7 ? 'Spring Wedding Season' : month >= 9 && month <= 11 ? 'Fall Wedding Season' : 'Wedding Planning Season'

  // ── Task 1: Weekly Instagram caption pack → email to founder ─────────────
  if (ADMIN_EMAIL) {
    const topics = [
      `Showcase a South Asian wedding photographer tip for ${season}`,
      `Why South Asian families choose vendors from Melaa.ca`,
      `Behind the scenes: what makes a great mehndi artist`,
      `3 questions to ask your wedding caterer before booking`,
      `Decorator spotlight: trending mandap styles in GTA ${new Date().getFullYear()}`,
      `Client story: finding the perfect DJ for a Punjabi wedding`,
      `Weekend inspo: South Asian wedding colour palettes`,
    ]

    const captions = await Promise.all(
      topics.map((t, i) =>
        ai(`Write an Instagram caption for Melaa.ca (South Asian wedding vendor directory in GTA). Topic: "${t}".
        Include 1 call to action to visit melaa.ca. Add 8 relevant hashtags at the end.
        Warm, community feel. Day ${i + 1} of 7.`, 200)
      )
    )

    const captionHtml = captions.map((c, i) =>
      `<div style="margin-bottom:20px;padding:16px;background:#fafaf7;border-radius:8px;border-left:3px solid #C8A96A">
        <p style="margin:0 0 6px;font-size:11px;font-weight:bold;color:#C8A96A;text-transform:uppercase">Day ${i + 1} — ${topics[i].split(':')[0]}</p>
        <p style="margin:0;color:#333;white-space:pre-wrap;font-size:13px">${c}</p>
      </div>`
    ).join('')

    await resend.emails.send({
      from: 'Melaa Marketing <agent@melaa.ca>',
      to: ADMIN_EMAIL,
      subject: `📱 This Week's Instagram Content Pack — 7 captions ready to post`,
      html: `<div style="font-family:sans-serif;max-width:650px;margin:0 auto">
        <h2 style="color:#C8A96A">Weekly Instagram Caption Pack</h2>
        <p>7 captions ready to copy-paste into Instagram. Post one per day for maximum reach.</p>
        ${captionHtml}
        <p style="color:#999;font-size:12px;margin-top:24px">Generated by Melaa Marketing Agent · ${now.toDateString()}</p>
      </div>`,
    })

    // Store in content_queue
    await supabase.from('content_queue').insert(
      captions.map((c, i) => ({
        type: 'instagram_caption',
        content: c,
        topic: topics[i],
        status: 'ready',
        scheduled_for: new Date(Date.now() + i * 24 * 60 * 60 * 1000).toISOString(),
      }))
    )
    results.push('instagram_pack:7_captions')
  }

  // ── Task 2: Buyer newsletter — goes to everyone who submitted a lead ──────
  const { data: buyers } = await supabase
    .from('leads')
    .select('buyer_email, buyer_name')
    .not('buyer_email', 'is', null)
    .gte('created_at', new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString())

  if (buyers && buyers.length > 0) {
    // Deduplicate
    const unique = Array.from(new Map(buyers.map(b => [b.buyer_email, b])).values()).slice(0, 200)

    const tip = await ai(`Write a short, warm wedding planning tip (3 sentences) for South Asian families in the GTA planning a wedding in ${season}. Practical, cultural, helpful.`)
    const vendorSpotlight = await ai(`Write a 2-sentence "vendor category spotlight" for South Asian wedding ${['photographers', 'decorators', 'mehndi artists', 'caterers'][Math.floor(Math.random() * 4)]} in GTA. What makes a great one? What to look for?`)

    // Get 3 featured vendors to spotlight
    const { data: featured } = await supabase
      .from('vendors')
      .select('name, slug, category:categories(name), city:cities(name)')
      .eq('is_active', true)
      .eq('is_featured', true)
      .limit(3)

    const vendorCards = (featured ?? []).map(v =>
      `<a href="${SITE}/vendors/${v.slug}" style="display:block;padding:12px;background:#fafaf7;border-radius:8px;margin-bottom:8px;text-decoration:none;color:#1A1A1A">
        <strong>${v.name}</strong>
        <span style="color:#C8A96A;font-size:12px;margin-left:8px">${(v.category as unknown as { name: string } | null)?.name ?? ''} · ${(v.city as unknown as { name: string } | null)?.name ?? ''}</span>
      </a>`
    ).join('')

    for (const buyer of unique) {
      if (!buyer.buyer_email) continue
      await resend.emails.send({
        from: 'Melaa Wedding Tips <hello@melaa.ca>',
        to: buyer.buyer_email,
        subject: `💍 ${season} wedding planning tips from Melaa`,
        html: `<div style="font-family:sans-serif;max-width:600px;margin:0 auto">
          <h2 style="color:#C8A96A">Hello${buyer.buyer_name ? `, ${buyer.buyer_name.split(' ')[0]}` : ''}! 👋</h2>
          <h3>Wedding Planning Tip</h3>
          <p style="color:#444">${tip}</p>
          <h3>Vendor Spotlight</h3>
          <p style="color:#444">${vendorSpotlight}</p>
          ${featured && featured.length > 0 ? `<h3>Featured Vendors This Week</h3>${vendorCards}` : ''}
          <div style="margin-top:20px">
            <a href="${SITE}/vendors" style="background:#C8A96A;color:white;padding:10px 20px;border-radius:20px;text-decoration:none">Browse All Vendors →</a>
          </div>
          <p style="color:#bbb;font-size:11px;margin-top:20px">You're receiving this because you submitted an inquiry on Melaa.ca. Reply to unsubscribe.</p>
        </div>`,
      })
    }
    results.push(`buyer_newsletter:${unique.length}_sent`)
  }

  // ── Task 3: Ad copy pack → email to founder ───────────────────────────────
  if (ADMIN_EMAIL) {
    const [metaAd, googleAd, tiktokAd] = await Promise.all([
      ai(`Write a Meta (Facebook/Instagram) ad for Melaa.ca — South Asian wedding vendor directory in GTA.
      Primary text (125 chars max), headline (40 chars), description (25 chars).
      Target: South Asian families in GTA planning a wedding. Season: ${season}.
      Format as: PRIMARY: ... | HEADLINE: ... | DESCRIPTION: ...`),
      ai(`Write 3 Google Search ad variants for Melaa.ca targeting "South Asian wedding vendors GTA".
      Each variant: Headline 1 (30 chars) | Headline 2 (30 chars) | Description (90 chars).
      Focus on trust, local, free to browse.`),
      ai(`Write a TikTok/Reels script hook (first 3 seconds) + caption for Melaa.ca.
      Target: young South Asian couples planning weddings in GTA. Trendy, authentic, not salesy. Under 150 words total.`),
    ])

    await resend.emails.send({
      from: 'Melaa Marketing <agent@melaa.ca>',
      to: ADMIN_EMAIL,
      subject: `🎯 Ad Copy Pack — Meta, Google, TikTok ready to run`,
      html: `<div style="font-family:sans-serif;max-width:650px;margin:0 auto">
        <h2 style="color:#C8A96A">Ad Copy Pack — ${season}</h2>
        <h3>Meta (Facebook/Instagram)</h3>
        <div style="background:#fafaf7;padding:16px;border-radius:8px;white-space:pre-wrap;font-size:13px">${metaAd}</div>
        <h3 style="margin-top:20px">Google Search Ads</h3>
        <div style="background:#fafaf7;padding:16px;border-radius:8px;white-space:pre-wrap;font-size:13px">${googleAd}</div>
        <h3 style="margin-top:20px">TikTok / Reels</h3>
        <div style="background:#fafaf7;padding:16px;border-radius:8px;white-space:pre-wrap;font-size:13px">${tiktokAd}</div>
        <p style="color:#999;font-size:12px;margin-top:24px">Generated by Melaa Marketing Agent · ${now.toDateString()}</p>
      </div>`,
    })
    results.push('ad_copy_pack:3_channels')
  }

  return NextResponse.json({ ok: true, agent: 'marketing', tasks: results, ran_at: now.toISOString() })
}
