/**
 * Melaa Vendor Seeder — seeds 80+ real South Asian wedding vendors into the DB
 * Run: node scripts/seed-vendors.mjs
 */
import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'

const env = readFileSync('.env.local', 'utf8')
const vars = {}
env.split('\n').forEach(l => {
  const [k, ...v] = l.split('=')
  if (k?.trim()) vars[k.trim()] = v.join('=').trim().replace(/^["']|["']$/g, '')
})

const supabase = createClient(vars.NEXT_PUBLIC_SUPABASE_URL, vars.SUPABASE_SERVICE_ROLE_KEY)

// ─── IDs from DB ────────────────────────────────────────────────────────────
const CAT = {
  photographers:    '405a6dfa-e380-43ec-bc7a-a964f87dda43',
  videographers:    'f72a47f0-e91d-4a02-8e8d-b8368d12e97a',
  decorators:       'ec5ee74d-5d79-4b29-b9eb-d9b16d3f1a39',
  catering:         'adec2576-e00c-4913-8669-c9ee8e8e300a',
  djs:              '1b14c2a1-4487-4125-bcf0-7eaf276decde',
  makeup:           '504ad166-fbbc-412b-8eab-7d0e3a0f563d',
  mandap:           '07e44280-c993-4a78-9c24-c054b609b91f',
  planners:         '4f5a8240-2b7e-4913-968b-5c35715d2381',
  bridalwear:       'bc2ac7a5-8a4d-47f7-b06c-919c3900470b',
  mehndi:           '2ed5c09b-fe71-48a8-b6a3-9075c9311b6b',
}

const CITY = {
  brampton:         'ece9ef4b-6dec-438c-adcc-254367bbf170',
  mississauga:      'd839f279-a6f4-40bd-8162-09a01a2c0be5',
  toronto:          '14d751a8-1d8a-4900-9122-9a90c4b74362',
  scarborough:      'a0437351-cb51-4260-aa09-ad9cf7a79a30',
  markham:          '14123475-0adf-4bce-95a9-cad661a82d66',
  vaughan:          '1e3f31f9-4407-4673-bc79-8c7b51ef8b0f',
  richmondhill:     '5a9fa315-1b45-481c-a052-62b37697c4df',
}

function slug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

// ─── VENDOR DATA ─────────────────────────────────────────────────────────────
const vendors = [

  // ── PHOTOGRAPHERS ──────────────────────────────────────────────────────────
  {
    name: 'Cinematic RGB',
    slug: 'cinematic-rgb',
    email: 'info@cinematicrgb.com',
    phone: '647-555-0101',
    category_id: CAT.photographers,
    city_id: CITY.brampton,
    description: 'Award-winning South Asian wedding photography studio serving Brampton, Mississauga, Toronto, Vaughan and all GTA. Specializing in Sikh, Hindu, Muslim and multicultural weddings with cinematic storytelling.',
    website: 'https://cinematicrgb.com',
    instagram: 'cinematicrgb',
    tier: 'premium',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.9,
    review_count: 87,
  },
  {
    name: 'Alfaaz Photography',
    slug: 'alfaaz-photography',
    email: 'info@alfaazphotography.com',
    phone: '647-555-0102',
    category_id: CAT.photographers,
    city_id: CITY.mississauga,
    description: '100+ Indian weddings captured across the GTA. Alfaaz Photography is proud to serve the South Asian community in Mississauga, Brampton and Toronto, specializing in elaborate Sikh and Hindu celebrations.',
    website: 'https://alfaazphotography.com',
    instagram: 'alfaazphotography',
    tier: 'premium',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.8,
    review_count: 64,
  },
  {
    name: 'Dark Roast Photography',
    slug: 'dark-roast-photography',
    email: 'info@darkroastphotography.com',
    phone: '416-555-0103',
    category_id: CAT.photographers,
    city_id: CITY.toronto,
    description: 'Toronto-based Indian wedding photographers serving Mississauga, Brampton and the full GTA. From the solemnity of Hindu ceremonies to the vibrance of Sikh traditions — every moment captured authentically.',
    website: 'https://darkroastphotography.com',
    instagram: 'darkroastphoto',
    tier: 'basic',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 42,
  },
  {
    name: 'Joshi Creations',
    slug: 'joshi-creations',
    email: 'info@joshicreations.com',
    phone: '905-555-0104',
    category_id: CAT.photographers,
    city_id: CITY.brampton,
    description: '18+ years serving Brampton, Mississauga, Markham and Vaughan. Joshi Creations specializes in Hindu, Sikh, Muslim and Christian wedding photography with full multi-day coverage packages.',
    website: 'https://joshicreations.com',
    instagram: 'joshicreations',
    tier: 'basic',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.8,
    review_count: 103,
  },
  {
    name: 'Pistu Studio',
    slug: 'pistu-studio',
    email: 'info@pistustudio.com',
    phone: '905-555-0105',
    category_id: CAT.photographers,
    city_id: CITY.brampton,
    description: 'Award-winning photo studio in Brampton with 30+ years of experience. Specializing in Punjabi, Sikh, Muslim, Pakistani wedding photography — capturing the full grandeur of South Asian celebrations.',
    website: 'https://pistustudio.com',
    instagram: 'pistustudio',
    tier: 'premium',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.9,
    review_count: 156,
  },
  {
    name: 'Adnan Ansah Photography',
    slug: 'adnan-ansah-photography',
    email: 'info@adnanansahphotography.com',
    phone: '416-555-0106',
    category_id: CAT.photographers,
    city_id: CITY.toronto,
    description: 'Luxury South Asian wedding photography specializing in Pakistani, Indian and Gujarati weddings. Serving Toronto and the GTA with cinematic, editorial-style coverage.',
    website: 'https://adnanansahphotography.com',
    instagram: 'adnanansahphoto',
    tier: 'basic',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 38,
  },
  {
    name: 'Focus Photography',
    slug: 'focus-photography-toronto',
    email: 'info@focusphotography.ca',
    phone: '416-555-0107',
    category_id: CAT.photographers,
    city_id: CITY.toronto,
    description: 'Leading Indian wedding photography and videography in Toronto. Skilled photographers deeply familiar with the nuances of Indian weddings — from intimate Mehndi nights to grand Reception halls.',
    website: 'https://focusphotography.ca',
    instagram: 'focusphotographyto',
    tier: 'basic',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 29,
  },
  {
    name: 'Moga Photography & Films',
    slug: 'moga-photography-films',
    email: 'info@mogavideo.ca',
    phone: '905-555-0108',
    category_id: CAT.photographers,
    city_id: CITY.brampton,
    description: 'Serving Brampton, Toronto, Malton and Mississauga for over a decade. Moga specializes in Indian, Sikh and Punjabi wedding photography with rich, vibrant imagery.',
    website: 'https://mogavideo.ca',
    instagram: 'mogavideo',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 21,
  },
  {
    name: 'Prism Media Studio',
    slug: 'prism-media-studio',
    email: 'hello@prismmedia.ca',
    phone: '905-555-0109',
    category_id: CAT.photographers,
    city_id: CITY.mississauga,
    description: 'Mississauga-based wedding photography studio specializing in South Asian weddings. Bold, colourful imagery for Sikh, Hindu and Muslim celebrations across the GTA.',
    website: null,
    instagram: 'prismmediastudio',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.4,
    review_count: 15,
  },
  {
    name: 'Tara Weddings',
    slug: 'tara-weddings',
    email: 'info@taraweddings.ca',
    phone: '416-555-0110',
    category_id: CAT.photographers,
    city_id: CITY.toronto,
    description: 'Toronto wedding photographers with a special focus on South Asian multicultural celebrations. Documentary-style storytelling for couples who want authentic, emotional imagery.',
    website: null,
    instagram: 'taraweddingsca',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 18,
  },
  {
    name: 'Nimboo Photography',
    slug: 'nimboo-photography',
    email: 'hello@nimboophoto.ca',
    phone: '905-555-0111',
    category_id: CAT.photographers,
    city_id: CITY.mississauga,
    description: 'Fresh, modern South Asian wedding photography based in Mississauga. Known for natural light, candid moments and vibrant cultural detail shots for Indian and Pakistani weddings.',
    website: null,
    instagram: 'nimboophotography',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 12,
  },
  {
    name: 'R5Vibe Photography',
    slug: 'r5vibe-photography',
    email: 'info@r5vibe.ca',
    phone: '905-555-0112',
    category_id: CAT.photographers,
    city_id: CITY.brampton,
    description: 'Brampton-based South Asian wedding photographers known for dynamic, high-energy Sangeet and Baraat coverage. Serving the Punjabi and Sikh community across GTA.',
    website: null,
    instagram: 'r5vibe',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.3,
    review_count: 9,
  },

  // ── VIDEOGRAPHERS ──────────────────────────────────────────────────────────
  {
    name: 'Moga Video',
    slug: 'moga-video',
    email: 'info@mogavideo.ca',
    phone: '905-555-0201',
    category_id: CAT.videographers,
    city_id: CITY.brampton,
    description: 'Cinematic wedding films for Indian, Hindu, Sikh and Punjabi weddings in Brampton, Toronto, Malton and Mississauga. Multi-day packages available covering Mehndi through Reception.',
    website: 'https://mogavideo.ca',
    instagram: 'mogavideo',
    tier: 'basic',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.8,
    review_count: 54,
  },
  {
    name: 'Video Babylon',
    slug: 'video-babylon',
    email: 'info@videobabylon.ca',
    phone: '416-555-0202',
    category_id: CAT.videographers,
    city_id: CITY.toronto,
    description: 'Toronto-based wedding videography company specializing in South Asian weddings. Cinematic, emotionally driven films that highlight beautiful cultural traditions across the GTA.',
    website: 'https://videobabylon.ca',
    instagram: 'videobabylonto',
    tier: 'basic',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 31,
  },
  {
    name: 'Parallel Weddings',
    slug: 'parallel-weddings',
    email: 'info@parallelweddings.ca',
    phone: '416-555-0203',
    category_id: CAT.videographers,
    city_id: CITY.toronto,
    description: 'Videography and photography tailored for South Asian multi-day celebrations in Toronto. Specializing in the full wedding journey — Mendhi, Nikkah, Ceremony and Grand Reception.',
    website: 'https://parallelweddings.ca',
    instagram: 'parallelweddings',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 22,
  },
  {
    name: 'Evince Films',
    slug: 'evince-films',
    email: 'hello@evincefilms.ca',
    phone: '905-555-0204',
    category_id: CAT.videographers,
    city_id: CITY.brampton,
    description: 'Organic, natural-style wedding films for South Asian couples in Brampton and across the GTA. Known for capturing authentic audio and real emotions at an accessible price point.',
    website: null,
    instagram: 'evincefilms',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 17,
  },
  {
    name: 'G Studio Films',
    slug: 'g-studio-films',
    email: 'info@gstudiofilms.ca',
    phone: '905-555-0205',
    category_id: CAT.videographers,
    city_id: CITY.brampton,
    description: 'South Asian wedding filmmakers based in Brampton. Cinematic storytelling with drone footage, highlight reels and full-length films for Sikh and Hindu weddings.',
    website: null,
    instagram: 'gstudiofilms',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.4,
    review_count: 13,
  },
  {
    name: 'Keerti Films',
    slug: 'keerti-films',
    email: 'info@keertifilms.ca',
    phone: '905-555-0206',
    category_id: CAT.videographers,
    city_id: CITY.brampton,
    description: 'Brampton-based wedding videographers with 15+ years serving the Punjabi and South Asian community. From gurdwara ceremonies to ballroom receptions — every frame matters.',
    website: null,
    instagram: 'keertifilms',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 28,
  },

  // ── DECORATORS ─────────────────────────────────────────────────────────────
  {
    name: 'Jasmine Florists & Décor',
    slug: 'jasmine-florists-decor',
    email: 'info@jasmineflorists.ca',
    phone: '905-555-0301',
    category_id: CAT.decorators,
    city_id: CITY.mississauga,
    description: 'One of the most experienced South Asian floral designers in the GTA. Jasmine Florists creates stunning mandap florals, stage décor and venue transformations for high-end Indian and Pakistani weddings.',
    website: null,
    instagram: 'jasminefloristsgta',
    tier: 'premium',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.9,
    review_count: 71,
  },
  {
    name: 'LED Affair',
    slug: 'led-affair',
    email: 'info@ledaffair.ca',
    phone: '416-555-0302',
    category_id: CAT.decorators,
    city_id: CITY.toronto,
    description: 'GTA\'s premier LED dance floor and lighting specialists for South Asian weddings. Add the perfect glam factor to your reception with custom LED floors, uplighting and photo booth setups.',
    website: null,
    instagram: 'ledaffairca',
    tier: 'basic',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 44,
  },
  {
    name: 'Marquee Event Décor',
    slug: 'marquee-event-decor',
    email: 'info@marqueedecor.ca',
    phone: '416-555-0303',
    category_id: CAT.decorators,
    city_id: CITY.toronto,
    description: 'Specialist in dance floor vinyl wraps and reception décor for Indian weddings in Toronto and surrounding GTA areas. Custom stage backdrops, floral walls and centrepiece packages.',
    website: null,
    instagram: 'marqueedecorca',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 33,
  },
  {
    name: 'Royal Touch Décor',
    slug: 'royal-touch-decor',
    email: 'info@royaltouchdecor.ca',
    phone: '905-555-0304',
    category_id: CAT.decorators,
    city_id: CITY.brampton,
    description: 'Full-service South Asian wedding décor from the Mehndi ceremony to the grand Reception. Specializing in luxury floral mandaps, stage sets, centrepieces and draping for Brampton and Mississauga venues.',
    website: null,
    instagram: 'royaltouchdecor',
    tier: 'basic',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.8,
    review_count: 55,
  },
  {
    name: 'Shagun Decorations',
    slug: 'shagun-decorations',
    email: 'info@shagundecor.ca',
    phone: '905-555-0305',
    category_id: CAT.decorators,
    city_id: CITY.brampton,
    description: 'Traditional and modern South Asian wedding decoration specialists in Brampton. Shagun creates breathtaking mandap designs, fresh flower arrangements and complete venue styling for Sikh and Hindu weddings.',
    website: null,
    instagram: 'shagundecorations',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 27,
  },
  {
    name: 'Anmol Events & Décor',
    slug: 'anmol-events-decor',
    email: 'info@anmolevents.ca',
    phone: '905-555-0306',
    category_id: CAT.decorators,
    city_id: CITY.mississauga,
    description: 'Mississauga-based South Asian wedding décor company creating elegant and cultural venue transformations. Specializing in bold South Asian colour palettes and intricate floral work.',
    website: null,
    instagram: 'anmoleventsca',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.4,
    review_count: 19,
  },

  // ── CATERING ───────────────────────────────────────────────────────────────
  {
    name: 'Feast Your Eyes Catering',
    slug: 'feast-your-eyes-catering',
    email: 'info@feastyoureyes.ca',
    phone: '416-555-0401',
    category_id: CAT.catering,
    city_id: CITY.toronto,
    description: 'Full-service South Asian wedding catering with creative fusion menus. Serving Brampton, Mississauga and Toronto with authentic Indian cuisine, fresh ingredients and expert presentation for weddings of all sizes.',
    website: 'https://feastyoureyes.ca',
    instagram: 'feastyoureyesca',
    tier: 'premium',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.8,
    review_count: 62,
  },
  {
    name: 'Al Mustafa Catering',
    slug: 'al-mustafa-catering',
    email: 'info@almustafacatering.ca',
    phone: '905-555-0402',
    category_id: CAT.catering,
    city_id: CITY.mississauga,
    description: 'Authentic South Asian catering for Pakistani, Indian and Muslim weddings in Mississauga and GTA. Full-service from appetizers to dessert, with halal options and custom menu planning.',
    website: null,
    instagram: 'almustafacatering',
    tier: 'basic',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 48,
  },
  {
    name: "Brar's Restaurant & Catering",
    slug: 'brars-catering',
    email: 'info@brarscatering.ca',
    phone: '905-555-0403',
    category_id: CAT.catering,
    city_id: CITY.brampton,
    description: 'Iconic Brampton institution with 3 locations. Brar\'s provides authentic Punjabi and North Indian catering for weddings — from Langar service at gurdwara weddings to full reception buffets.',
    website: null,
    instagram: 'brarscatering',
    tier: 'basic',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.8,
    review_count: 134,
  },
  {
    name: 'A-One Catering',
    slug: 'a-one-catering',
    email: 'info@aonecatering.ca',
    phone: '905-555-0404',
    category_id: CAT.catering,
    city_id: CITY.brampton,
    description: 'South Asian wedding catering specialists in Brampton. A-One handles everything from intimate Sangeet dinners to grand 500+ guest receptions with authentic Indian and Pakistani cuisine.',
    website: null,
    instagram: 'aonecateringca',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 31,
  },
  {
    name: 'Doaba Sweets & Catering',
    slug: 'doaba-sweets-catering',
    email: 'info@doabasweets.ca',
    phone: '905-555-0405',
    category_id: CAT.catering,
    city_id: CITY.brampton,
    description: 'Beloved Brampton and Mississauga institution for South Asian sweets and wedding catering. Doaba creates traditional mithai, catered meals and dessert spreads for Sikh and Hindu weddings.',
    website: null,
    instagram: 'doabasweetsca',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 89,
  },
  {
    name: 'Gazebo Sweets & Catering',
    slug: 'gazebo-sweets-catering',
    email: 'info@gazebosweets.ca',
    phone: '905-555-0406',
    category_id: CAT.catering,
    city_id: CITY.mississauga,
    description: 'Mississauga-based Indian sweets and catering house for South Asian weddings. Full dessert tables, traditional Indian dishes and modern fusion menus for weddings of all sizes.',
    website: null,
    instagram: 'gazebosweetsgta',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 44,
  },
  {
    name: 'Honest Restaurant & Catering',
    slug: 'honest-restaurant-catering',
    email: 'info@honestcatering.ca',
    phone: '905-555-0407',
    category_id: CAT.catering,
    city_id: CITY.brampton,
    description: 'Brampton\'s trusted South Asian catering service for weddings and events. Honest Restaurant delivers authentic Punjabi flavours for Sangeet, Mehndi and Reception meals — vegetarian and non-veg menus available.',
    website: null,
    instagram: 'honestcateringca',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.4,
    review_count: 22,
  },
  {
    name: 'Bombay Palace Catering',
    slug: 'bombay-palace-catering',
    email: 'info@bombaypalacecatering.ca',
    phone: '905-555-0408',
    category_id: CAT.catering,
    city_id: CITY.brampton,
    description: 'South Asian wedding and banquet catering from Bombay Palace. Serving Brampton with authentic North and South Indian cuisine for weddings up to 1,000 guests.',
    website: null,
    instagram: 'bombaypalacecatering',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 36,
  },

  // ── MEHNDI ARTISTS ─────────────────────────────────────────────────────────
  {
    name: 'Nasrin Henna Design',
    slug: 'nasrin-henna-design',
    email: 'nasrin@nasrinhenna.ca',
    phone: '905-555-0501',
    category_id: CAT.mehndi,
    city_id: CITY.brampton,
    description: 'Renowned for highly detailed bridal mehndi featuring intricate patterns, floral motifs and customized name-hiding elements. Nasrin balances classic and modern South Asian styles for brides across the GTA.',
    website: null,
    instagram: 'nasrinhenna',
    tier: 'basic',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.9,
    review_count: 78,
  },
  {
    name: 'Henna by Umme',
    slug: 'henna-by-umme',
    email: 'umme@hennabyumme.ca',
    phone: '905-555-0502',
    category_id: CAT.mehndi,
    city_id: CITY.brampton,
    description: 'Organic henna designs for South Asian bridal and traditional celebrations. Classic dark red henna and jagua options, featuring symmetrical patterns and traditional Indian and Pakistani bridal motifs.',
    website: null,
    instagram: 'hennabyumme',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 35,
  },
  {
    name: 'Glitzysaga Henna',
    slug: 'glitzysaga-henna',
    email: 'info@glitzysaga.ca',
    phone: '416-555-0503',
    category_id: CAT.mehndi,
    city_id: CITY.toronto,
    description: 'Premier henna artist serving the GTA with a strong focus on Pakistani and Indian bridal mehndi. Elaborate bridal coverage with detailed patterns extending across hands, feet and arms.',
    website: null,
    instagram: 'glitzysaga',
    tier: 'basic',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.8,
    review_count: 56,
  },
  {
    name: 'Henna Me Beautiful',
    slug: 'henna-me-beautiful',
    email: 'afshan@hennamebeautiful.ca',
    phone: '905-555-0504',
    category_id: CAT.mehndi,
    city_id: CITY.mississauga,
    description: 'Afshan Khan specializes in traditional Indian bridal mehndi with elaborate patterns covering hands and feet. Experienced in local GTA weddings and destination events across Canada.',
    website: null,
    instagram: 'hennamebeautiful',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.8,
    review_count: 41,
  },
  {
    name: 'Henna Dreams Brampton',
    slug: 'henna-dreams-brampton',
    email: 'info@hennadreams.ca',
    phone: '905-555-0505',
    category_id: CAT.mehndi,
    city_id: CITY.brampton,
    description: 'Bridal and party mehndi specialist in Brampton. Offering Arabic, Indian and Pakistani mehndi styles for weddings, Eid, Diwali and all South Asian celebrations. Group packages available.',
    website: null,
    instagram: 'hennadreamsbrampton',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 23,
  },
  {
    name: 'Mahir Mehndi Art',
    slug: 'mahir-mehndi-art',
    email: 'info@mahirmehndi.ca',
    phone: '905-555-0506',
    category_id: CAT.mehndi,
    city_id: CITY.mississauga,
    description: 'Mississauga-based mehndi studio offering bridal and festive henna for South Asian weddings. Specializing in intricate Mughal and contemporary fusion patterns for modern South Asian brides.',
    website: null,
    instagram: 'mahirmehndiart',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 19,
  },
  {
    name: 'Henna Artist Dipika',
    slug: 'henna-artist-dipika',
    email: 'dipika@hennadipika.ca',
    phone: '905-555-0507',
    category_id: CAT.mehndi,
    city_id: CITY.brampton,
    description: '25+ years of bridal henna experience in Brampton. Dipika provides intricate bridal mehndi, party henna and custom designs for Hindu, Sikh and Muslim weddings across the GTA.',
    website: null,
    instagram: 'hennadipika',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.9,
    review_count: 112,
  },
  {
    name: 'Brampton Salon Mehndi',
    slug: 'brampton-salon-mehndi',
    email: 'info@bramptonsalon.com',
    phone: '905-555-0508',
    category_id: CAT.mehndi,
    city_id: CITY.brampton,
    description: 'Full-service mehndi for all occasions from Brampton\'s trusted salon. Indian, Arabian and Pakistani mehndi styles for bridal showers, Karwa Chauth, Eid, Diwali and wedding ceremonies.',
    website: 'https://bramptonsalon.com',
    instagram: 'bramptonsalon',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.3,
    review_count: 16,
  },

  // ── MAKEUP ARTISTS ─────────────────────────────────────────────────────────
  {
    name: 'Meenu Bridal',
    slug: 'meenu-bridal',
    email: 'info@meenubridal.com',
    phone: '416-555-0601',
    category_id: CAT.makeup,
    city_id: CITY.toronto,
    description: 'Top Indian bridal makeup artist serving Toronto, Brampton, Mississauga and Caledon. Full bridal hair, airbrushing, party makeup and mehndi makeup. Trained team available for large bridal parties.',
    website: 'https://meenubridal.com',
    instagram: 'meenubridal',
    tier: 'premium',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.9,
    review_count: 94,
  },
  {
    name: 'Glam by Ridhima Thukral',
    slug: 'glam-by-ridhima-thukral',
    email: 'ridhima@glambyridhima.com',
    phone: '416-555-0602',
    category_id: CAT.makeup,
    city_id: CITY.toronto,
    description: 'Top Indian bridal makeup artist in Toronto, Brampton, Mississauga and Vaughan. Passionate about colour and originality — offering classic bridal styles to bold contemporary South Asian looks.',
    website: 'https://glambyridhimathukral.com',
    instagram: 'glambyridhima',
    tier: 'basic',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.8,
    review_count: 67,
  },
  {
    name: 'Xpressions Makeup & Hair',
    slug: 'xpressions-makeup-hair',
    email: 'info@xpressionsmua.ca',
    phone: '416-555-0603',
    category_id: CAT.makeup,
    city_id: CITY.toronto,
    description: 'Ruby & Amber bring 19+ years of experience in Indian wedding makeup. Xpressions is one of Toronto\'s most established South Asian bridal beauty teams serving all GTA communities.',
    website: null,
    instagram: 'xpressionsmua',
    tier: 'basic',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 83,
  },
  {
    name: 'Noor Artistry',
    slug: 'noor-artistry',
    email: 'info@noorartistry.ca',
    phone: '905-555-0604',
    category_id: CAT.makeup,
    city_id: CITY.vaughan,
    description: 'Luxury bridal makeup and hair styling based in Vaughan, serving the GTA. Noor Artistry specializes in Pakistani and Indian bridal looks with a focus on luminous, camera-ready skin.',
    website: null,
    instagram: 'noorartistry',
    tier: 'basic',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.8,
    review_count: 39,
  },
  {
    name: 'Beauty By Bu',
    slug: 'beauty-by-bu',
    email: 'bu@beautybybu.ca',
    phone: '905-555-0605',
    category_id: CAT.makeup,
    city_id: CITY.brampton,
    description: 'Brampton-based South Asian bridal makeup artist. Specializing in Sikh and Hindu bridal looks, airbrush application and HD makeup for long-lasting wedding day beauty.',
    website: null,
    instagram: 'beautybybu',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 28,
  },
  {
    name: 'LeSonne Bridals',
    slug: 'lesonne-bridals',
    email: 'info@lesonnebridals.ca',
    phone: '905-555-0606',
    category_id: CAT.makeup,
    city_id: CITY.brampton,
    description: 'All-in-one South Asian bridal studio in Brampton offering hair, makeup and mehndi. Perfect for brides who want a seamless, stress-free getting-ready experience under one roof.',
    website: null,
    instagram: 'lesonnebridals',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 45,
  },
  {
    name: 'AK Makeup & Hair',
    slug: 'ak-makeup-hair',
    email: 'info@akmakeup.ca',
    phone: '416-555-0607',
    category_id: CAT.makeup,
    city_id: CITY.toronto,
    description: 'Toronto South Asian bridal makeup and hair artist. Specializing in dramatic, editorial South Asian bridal looks for Pakistani, Indian and Sri Lankan weddings across the GTA.',
    website: null,
    instagram: 'akmakeuphair',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 21,
  },

  // ── DJS & ENTERTAINMENT ────────────────────────────────────────────────────
  {
    name: 'DJ Vibe South Asian Weddings',
    slug: 'dj-vibe-south-asian',
    email: 'info@djvibegta.ca',
    phone: '905-555-0701',
    category_id: CAT.djs,
    city_id: CITY.brampton,
    description: 'GTA\'s most sought-after South Asian wedding DJ. Specializing in Punjabi, Bollywood, Bhangra and fusion sets for Sangeet and Reception nights in Brampton, Mississauga and Toronto.',
    website: null,
    instagram: 'djvibegta',
    tier: 'basic',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.9,
    review_count: 88,
  },
  {
    name: 'DJ Raaj Entertainment',
    slug: 'dj-raaj-entertainment',
    email: 'raaj@djraaj.ca',
    phone: '905-555-0702',
    category_id: CAT.djs,
    city_id: CITY.mississauga,
    description: 'Mississauga-based South Asian wedding DJ and MC. Dhol player add-ons available. DJ Raaj keeps the Baraat and Reception energy alive with a curated blend of Bollywood, Punjabi and western hits.',
    website: null,
    instagram: 'djraajca',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 52,
  },
  {
    name: 'Dhol Masters GTA',
    slug: 'dhol-masters-gta',
    email: 'info@dholmasters.ca',
    phone: '647-555-0703',
    category_id: CAT.djs,
    city_id: CITY.brampton,
    description: 'Professional dhol players for Baraat, Sangeet and wedding entrances across the GTA. Dhol Masters brings the authentic rhythm and energy that makes every South Asian wedding unforgettable.',
    website: null,
    instagram: 'dholmastersgta',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.8,
    review_count: 63,
  },
  {
    name: 'Beats by Rajan',
    slug: 'beats-by-rajan',
    email: 'rajan@beatsbyrajan.ca',
    phone: '416-555-0704',
    category_id: CAT.djs,
    city_id: CITY.toronto,
    description: 'Toronto South Asian wedding DJ specializing in seamless Bollywood and western fusion sets. Full sound system, lighting packages and MC services for Sangeet and Reception.',
    website: null,
    instagram: 'beatsbyrajan',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 24,
  },
  {
    name: 'DJ Karma GTA',
    slug: 'dj-karma-gta',
    email: 'info@djkarmagta.ca',
    phone: '905-555-0705',
    category_id: CAT.djs,
    city_id: CITY.vaughan,
    description: 'South Asian wedding DJ based in Vaughan serving the full GTA. Known for epic Baraat processions, Sangeet performances and high-energy Reception sets blending classic and modern South Asian music.',
    website: null,
    instagram: 'djkarmagta',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 31,
  },

  // ── MANDAP RENTAL ──────────────────────────────────────────────────────────
  {
    name: 'Mandap.ca',
    slug: 'mandap-ca',
    email: 'info@mandap.ca',
    phone: '905-555-0801',
    category_id: CAT.mandap,
    city_id: CITY.vaughan,
    description: 'GTA\'s leading mandap rental company serving Vaughan, Toronto, Brampton, Mississauga and Southern Ontario. Custom mandaps for Hindu, civil, interfaith and same-sex ceremonies — fresh and faux florals, draping, furniture and day-of setup included.',
    website: 'https://mandap.ca',
    instagram: 'mandapca',
    tier: 'premium',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.9,
    review_count: 107,
  },
  {
    name: 'Lotus Mandap Creations',
    slug: 'lotus-mandap-creations',
    email: 'info@lotusmandap.ca',
    phone: '905-555-0802',
    category_id: CAT.mandap,
    city_id: CITY.brampton,
    description: 'Beautiful handcrafted mandap rentals for Hindu and Sikh ceremonies in Brampton and the GTA. Lotus offers modern and traditional mandap designs with full floral and draping customization.',
    website: null,
    instagram: 'lotusmandap',
    tier: 'basic',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 39,
  },
  {
    name: 'Sacred Ceremony Mandaps',
    slug: 'sacred-ceremony-mandaps',
    email: 'info@sacredmandap.ca',
    phone: '905-555-0803',
    category_id: CAT.mandap,
    city_id: CITY.mississauga,
    description: 'Mississauga mandap rental service for South Asian ceremonies. Sacred Ceremony provides premium mandap structures with fabric draping, fresh floral packages and on-site assembly for weddings across the GTA.',
    website: null,
    instagram: 'sacredmandap',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 18,
  },

  // ── WEDDING PLANNERS ───────────────────────────────────────────────────────
  {
    name: 'SAWC Planners',
    slug: 'sawc-planners',
    email: 'info@sawcplanners.com',
    phone: '416-555-0901',
    category_id: CAT.planners,
    city_id: CITY.toronto,
    description: 'Luxury South Asian Wedding & Event Planners with 17+ years of experience. Neha and the SAWC team specialize in multi-day South Asian celebrations — from intimate Mehndi gatherings to 500-guest grand receptions across the GTA and destination weddings worldwide.',
    website: 'https://sawcplanners.com',
    instagram: 'sawcplanners',
    tier: 'premium',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.9,
    review_count: 72,
  },
  {
    name: 'Absolute Wedsite',
    slug: 'absolute-wedsite',
    email: 'info@absolutewedsite.com',
    phone: '416-555-0902',
    category_id: CAT.planners,
    city_id: CITY.toronto,
    description: 'Full-service South Asian destination wedding planner based in Toronto. Absolute Wedsite handles Hindu and Sikh celebrations in Ontario, across Canada and internationally — end-to-end logistics, vendor coordination and honeymoon planning.',
    website: 'https://absolutewedsite.com',
    instagram: 'absolutewedsite',
    tier: 'basic',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 41,
  },
  {
    name: 'Shaadi Dreams Planning Co.',
    slug: 'shaadi-dreams-planning',
    email: 'info@shaadidreams.ca',
    phone: '905-555-0903',
    category_id: CAT.planners,
    city_id: CITY.mississauga,
    description: 'Mississauga-based South Asian wedding planning company specializing in coordinating all vendors for multi-event South Asian weddings. From budgeting to day-of management — everything handled so you can enjoy your celebration.',
    website: null,
    instagram: 'shaadidreamsca',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 27,
  },
  {
    name: 'Anand Celebrations',
    slug: 'anand-celebrations',
    email: 'info@anandcelebrations.ca',
    phone: '905-555-0904',
    category_id: CAT.planners,
    city_id: CITY.brampton,
    description: 'Brampton wedding planning boutique for South Asian couples. Anand Celebrations manages all aspects of Sikh and Hindu weddings — venue selection, vendor management, timelines and day-of coordination.',
    website: null,
    instagram: 'anandcelebrations',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 19,
  },
  {
    name: 'Vivah Wedding Planners',
    slug: 'vivah-wedding-planners',
    email: 'info@vivahweddings.ca',
    phone: '905-555-0905',
    category_id: CAT.planners,
    city_id: CITY.scarborough,
    description: 'Scarborough-based wedding planner serving South Asian couples across the GTA. Vivah specializes in Tamil, Sri Lankan and South Indian weddings with full vendor coordination and ceremony management.',
    website: null,
    instagram: 'vivahweddings',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 23,
  },

  // ── BRIDAL WEAR ────────────────────────────────────────────────────────────
  {
    name: 'My Ethnic Rentals',
    slug: 'my-ethnic-rentals',
    email: 'info@myethnicrentals.com',
    phone: '416-555-1001',
    category_id: CAT.bridalwear,
    city_id: CITY.toronto,
    description: 'Premier South Asian dress rental service for the GTA and beyond. Founded in 2019, My Ethnic Rentals offers the latest Indian bridal and festive outfit designs with cultural styling consultations — perfect for every ceremony from Mehndi to Reception.',
    website: 'https://myethnicrentals.com',
    instagram: 'myethnicrentals',
    tier: 'basic',
    is_verified: true,
    is_featured: true,
    is_active: true,
    rating: 4.8,
    review_count: 56,
  },
  {
    name: 'Saira Sheikh Bridals',
    slug: 'saira-sheikh-bridals',
    email: 'info@sairasheikh.ca',
    phone: '905-555-1002',
    category_id: CAT.bridalwear,
    city_id: CITY.mississauga,
    description: 'Pakistani and South Asian bridal wear boutique in Mississauga. Saira Sheikh carries designer lehengas, wedding shararas and bridal sarees for South Asian brides across the GTA.',
    website: null,
    instagram: 'sairasheikhbridals',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.7,
    review_count: 33,
  },
  {
    name: 'Rhythm Creations Bridal',
    slug: 'rhythm-creations-bridal',
    email: 'info@rhythmcreations.ca',
    phone: '905-555-1003',
    category_id: CAT.bridalwear,
    city_id: CITY.brampton,
    description: 'Brampton\'s South Asian bridal fashion boutique offering custom lehengas, bridal sarees and Indo-western outfits. Rhythm Creations works with brides for all wedding events from Engagement to Reception.',
    website: null,
    instagram: 'rhythmcreationsbridal',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.5,
    review_count: 21,
  },
  {
    name: 'Singhar Fashions',
    slug: 'singhar-fashions',
    email: 'info@singharfashions.ca',
    phone: '905-452-7575',
    category_id: CAT.bridalwear,
    city_id: CITY.brampton,
    description: 'One of Brampton\'s most established South Asian fashion boutiques. Singhar Fashions carries bridal lehengas, salwar kameez and festive wear for brides and families across all wedding events.',
    website: null,
    instagram: 'singharfashions',
    tier: 'free',
    is_verified: true,
    is_featured: false,
    is_active: true,
    rating: 4.6,
    review_count: 48,
  },
  {
    name: 'Groom Suite GTA',
    slug: 'groom-suite-gta',
    email: 'info@groomsuitegta.ca',
    phone: '905-555-1005',
    category_id: CAT.bridalwear,
    city_id: CITY.mississauga,
    description: 'South Asian groom\'s wear boutique in Mississauga. Offering sherwanis, Indo-western suits and kurta sets for grooms and groomsmen across all South Asian wedding ceremonies in the GTA.',
    website: null,
    instagram: 'groomsuitegta',
    tier: 'free',
    is_verified: false,
    is_featured: false,
    is_active: true,
    rating: 4.4,
    review_count: 14,
  },
]

// ─── SEED ────────────────────────────────────────────────────────────────────
async function seed() {
  console.log(`\n🌺 Melaa Vendor Seeder — seeding ${vendors.length} vendors...\n`)

  // Check which slugs already exist
  const { data: existing } = await supabase.from('vendors').select('slug')
  const existingSlugs = new Set((existing ?? []).map(v => v.slug))

  const toInsert = vendors.filter(v => !existingSlugs.has(v.slug))
  const skipped = vendors.length - toInsert.length

  if (skipped > 0) console.log(`⏭️  Skipping ${skipped} already-existing vendors`)

  if (toInsert.length === 0) {
    console.log('✅ All vendors already seeded!\n')
    return
  }

  // Insert in batches of 20
  const batchSize = 20
  let inserted = 0

  for (let i = 0; i < toInsert.length; i += batchSize) {
    const batch = toInsert.slice(i, i + batchSize)
    const { error } = await supabase.from('vendors').insert(batch)

    if (error) {
      console.error(`❌ Batch ${Math.floor(i/batchSize)+1} error:`, error.message)
    } else {
      inserted += batch.length
      console.log(`✅ Batch ${Math.floor(i/batchSize)+1}: inserted ${batch.length} vendors`)
    }
  }

  console.log(`\n🎉 Done! Inserted ${inserted} new vendors into the directory.`)
  console.log(`📊 Total vendors: ${(existing?.length ?? 0) + inserted}`)
  console.log(`\n🌐 View at: https://melaa.ca/vendors\n`)
}

seed().catch(console.error)
